[package]
name = "salty_bet_bot"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
csv = "1.0.0-beta.5"
regex = "0.2.6"
#chrono = "0.4.0"
lazy_static = "1.0.0"
#nn = "0.1.6"
stdweb = "0.4.0"
rayon = "1.0.0"
serde = "1.0.27"
serde_json = "1.0.10"
serde_derive = "1.0.27"
