[package]
name = "salty_bet_bot"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
csv = "1.0.0-beta.5"
regex = "0.2.5"
#chrono = "0.4.0"
lazy_static = "1.0.0"
lyon_bezier = "0.8.5"
rand = "0.4.1"
#nn = "0.1.6"
stdweb = "0.3.0"
rayon = "0.9.0"
