[package]
name = "salty_bet_bot"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
algorithm = { path = "./algorithm" }
lazy_static = "1.0.0"
stdweb = "0.4.0"
stdweb-derive = "0.4.0"
serde = "1.0.27"
serde_json = "1.0.10"
serde_derive = "1.0.27"
